// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtwevZT_V8eDGsOn3hCWCdacsZTH4Tn5c',
    appId: '1:736274508794:android:044d8d821e7be10631d243',
    messagingSenderId: '736274508794',
    projectId: 'receipt-manager-app-a3d31',
    storageBucket: 'receipt-manager-app-a3d31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCepLQLHO1W_o_xEKMJfHPq7YM5AB_h5tM',
    appId: '1:736274508794:ios:ffa34c2054448d2c31d243',
    messagingSenderId: '736274508794',
    projectId: 'receipt-manager-app-a3d31',
    storageBucket: 'receipt-manager-app-a3d31.firebasestorage.app',
    iosBundleId: 'com.tamk2024sp.receiptManager',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAJSqP7x1b68f7CtoUF8lrzbCbwQBJlPM',
    appId: '1:736274508794:web:1aafb3af7ef53ec031d243',
    messagingSenderId: '736274508794',
    projectId: 'receipt-manager-app-a3d31',
    authDomain: 'receipt-manager-app-a3d31.firebaseapp.com',
    storageBucket: 'receipt-manager-app-a3d31.firebasestorage.app',
    measurementId: 'G-W85CNGMFCN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCepLQLHO1W_o_xEKMJfHPq7YM5AB_h5tM',
    appId: '1:736274508794:ios:ffa34c2054448d2c31d243',
    messagingSenderId: '736274508794',
    projectId: 'receipt-manager-app-a3d31',
    storageBucket: 'receipt-manager-app-a3d31.firebasestorage.app',
    iosBundleId: 'com.tamk2024sp.receiptManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAJSqP7x1b68f7CtoUF8lrzbCbwQBJlPM',
    appId: '1:736274508794:web:93b32b7f2ea0c85c31d243',
    messagingSenderId: '736274508794',
    projectId: 'receipt-manager-app-a3d31',
    authDomain: 'receipt-manager-app-a3d31.firebaseapp.com',
    storageBucket: 'receipt-manager-app-a3d31.firebasestorage.app',
    measurementId: 'G-HEYTFKBT8D',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAAJSqP7x1b68f7CtoUF8lrzbCbwQBJlPM',
    appId: '1:736274508794:web:1aafb3af7ef53ec031d243',
    messagingSenderId: '736274508794',
    projectId: 'receipt-manager-app-a3d31',
    authDomain: 'receipt-manager-app-a3d31.firebaseapp.com',
    storageBucket: 'receipt-manager-app-a3d31.firebasestorage.app',
    measurementId: 'G-W85CNGMFCN',
  );

}